### ISSUE TITLE
How to load sparse pruned model?

### ISSUE THREAD

**Issue by dmitrijeuseew** [intel/neural-compressor#1071]
@YIYANGCAI Hi, thank you very much for your examples with pruning of BERT for question answering. Could you please tell how to load a pruned model from checkpoints, so that it will load in sparse mode and so consume less memory (RAM and GPU) than initial (not pruned) model?

**Comment by YIYANGCAI** [comment]
Thanks for your comments and attention on INC.

I am not really sure which example of pruning BERT of Q&A you are referring at because we have different examples on it.

- If you are referring to [general pruning example](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager), you can use [pattern lock](https://github.com/intel/neural-compressor/tree/master/neural_compressor/compression/pruner#pruning-types) mode to load your sparse model for inference or re-training purpose. However, sparse models' memory footprints are nearly identical to dense ones because their difference are simply locate at weight values (zero or non-zero), unless kernels with corresponding sparse patterns are applied. I recommend you to refer to [ITREX](https://github.com/intel/intel-extension-for-transformers) for more information of deploying sparse models on Intel's hardware.
- If you are referring to [model slim example](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/question-answering/model_slim), this example applies channel-wise pruning and remove sparse weight channels/attention heads permanently. By running this example, you can observe how we really "prune" a sparse model, reduce its memory and accelerate its inference under common frameworks (PyTorch, etc.). 

I hope this response can help with your concern.
