### ISSUE TITLE
Feature Request: Pruning Callback for pytorch lightning

### ISSUE THREAD

**Issue by lminer** [intel/neural-compressor#1078]
Pytorch lighning is very popular among torch users. It would be great to have a pruning callback for pytorch lightning.

**Comment by PenghuiCheng** [comment]
Hi, Lminer,  glad to see your suggestion. We will first evaluate whether the current API meets the requirements of lighting.

**Comment by chensuyue** [comment]
Hi @lminer after some investigate, we decided not support pytorch lightning in short time. Thanks again for your comments!

**Comment by clementpoiret** [comment]
@lminer I had to develop my own callbacks, they are not extensively tested because they are very recent and because I tested them only on toy models, but you can find them here to try :) https://github.com/clementpoiret/lightning-nc

I set the requirements fairly high, but I believe they could be lowered.

**Comment by lminer** [comment]
Wow, that looks great!
