### ISSUE TITLE
[INT8_PTQ_STATIC] could not get symetric quant model when setting ['activation']['scheme'] = '

### ISSUE THREAD

**Issue by JiliangNi** [intel/neural-compressor#1110]

**Comment by JiliangNi** [comment]
@tybulewicz @dzungductran @macsz @kding1 

When I tried to do PTQ with PostTrainingQuantConfig(op_name_dict=op_name_dict)
op_name_dict = 
{
    ".*?": {
        "activation": {
            "granularity": ["per_tensor"], 
            "scheme": ["sym"], 
            "dtype": ["int8"], 
            "algorithm": ["kl"]
        }, 
        "weight": {
            "granularity": ["per_tensor"], 
![Uploading quant_setting.jpg…]()

![Uploading int8_model_with_uint_asym_node.jpg…]()

            "scheme": ["sym"], 
            "dtype": ["int8"],
            "algorithm": ["minmax"]
        }
}
I just got a Quantized model with some y_zero_point != 0 and type as uint8.
Did I miss something needed to be set for making ['int8'] and ['sym'] become effective?
Can anyone help me? Appreciated!

**Comment by xin3he** [comment]
Hi, @JiliangNi  It's because the dtype of activation in PyTorch is always torch.quint8, so the zero_point is 127 for sym.

**Comment by JiliangNi** [comment]
Thanks for applying! However, it's onnx model and its adaptor shows as onnxrt.py. In addition, I am wondering why op_name_dict['activation']['int8'] does not take effect.

**Comment by xin3he** [comment]
@yuwenzho Do you have any ideas?

**Comment by yuwenzho** [comment]
Hi @JiliangNi , this is because we have set the activations `dtype` to always be `uint8`, and `scheme` to always be `asym` in ONNX quantization. Any settings that exceed the capabilities of ONNX quantization will not take effect. 

You can refer to [onnxrt.yaml](https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/onnxrt.yaml), [onnxrt_cuda.yaml](https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/onnxrt_cuda.yaml), [onnxrt_dnnl.yaml](https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/onnxrt_dnnl.yaml), [onnxrt_trt.yaml](https://github.com/intel/neural-compressor/blob/master/neural_compressor/adaptor/onnxrt_trt.yaml) files for details about quantization capabilities of different Execution Providers. If you want to set up like you described above, you can try modifying the yaml file directly。

**Comment by yuwenzho** [comment]
Hi @JiliangNi
Currently, we do not support quantizing the Flatten op, but we have plans to support it in the future. Hope you can keep following our project:blush:. 

As for the input nodes you mentioned, when quantizing ONNX models, we generally don't quantize the input nodes because they typically represent the input data to the model.

**Comment by JiliangNi** [comment]
"Currently, we do not support quantizing the Flatten op, but we have plans to support it in the future. Hope you can keep following our projectblush."
- I will certainly keep following this project. Look forward to the new feature coming!

"As for the input nodes you mentioned, when quantizing ONNX models, we generally don't quantize the input nodes because they typically represent the input data to the model."
- I understand what you said about the input node. But the problem is that if you don't quantize the input node, the node below it will be affected. For example, if a Conv node below input node is quantized and the input node isn't quantized, the graph will look like   input -> QuantizeLinear -> QLinearConv -> DequantizeLinear. And the QuantizeLinear node will have a uint8, non-zero y_zero_point, meaning "asym" when other nodes all have int8 zero y_zero_point. It finally causes the int8 model cannot be inferred in onnxruntime.

My solution here is setting "input node and flatten node should be quantized" during calibration by hard code. Could you offer me any solution without changing the lib code?

**Comment by yuwenzho** [comment]
> For example, if a Conv node below input node is quantized and the input node isn't quantized, the graph will look like **input -> QuantizeLinear -> QLinearConv -> DequantizeLinear**

Assuming the input is of type float32, the QuantizeLinear operation will quantize the input tensor to uint8 (the same type as y_zero_point in the QuantizeLinear), and then serve as one of the inputs for the next QLinearConv. I'm not sure if this is what you meant by "quantize input node". If you expect to generate a graph in the form of "input -> QLinearConv -> DequantizeLinear", it is not supported currently. 

> other nodes all have int8 zero y_zero_point

Do you use neural-compressor to generate the quantized model? We have set the activation data type to uint8 for all ops, so no node should have an int8 y_zero_point.

> It finally causes the int8 model cannot be inferred in onnxruntime.

If possible, you can provide the error infomation, model and script for us to debug.

> I've supported Flatten op by changing code as below

Thanks for your suggestion and contribution! I will add it in a PR later. You can fork your own copy of intel/neural-compressor repository and modify the code to meet your current needs.

**Comment by hshen14** [comment]
@JiliangNi Please kindly verify the PR (https://github.com/intel/neural-compressor/pull/1151). We probably can close the issue if the PR solves your issue. Thanks.
