### ISSUE TITLE
Resnet Onnx example breaks with Windows11 WSL2

### ISSUE THREAD

**Issue by R4ZZ3** [intel/neural-compressor#121]
Hi,

Is it possible to run this with WSL2?
The ONNX Resnet example breaks with Windows11 WSL2

![image](https://user-images.githubusercontent.com/25264037/198390108-73e881f5-a018-454f-b2b7-e9699165b593.png)

**Comment by chensuyue** [comment]
Hi, thanks for raising the issue. 
We test with Win10 + WSL1 + onnx rn50 and it works. 
Which INC version did you test for?

**Comment by R4ZZ3** [comment]
1.14.1
I also tried the non-custom examples and it also ran into error. 

![image](https://user-images.githubusercontent.com/25264037/198875096-8695b4c1-096c-4233-8d08-508838128f0e.png)
wsl version 
![image](https://user-images.githubusercontent.com/25264037/198875111-8648fbb1-9fc6-481b-b44e-cab66ad2f797.png)

Using Ubuntu 20.04LTS as my WSL2 distro
![image](https://user-images.githubusercontent.com/25264037/198875158-eb614268-6a77-45d8-a15b-4f7b8619d42a.png)

**Comment by chensuyue** [comment]
Hi, we reproduced your issue on windows, debug in progress.

**Comment by chensuyue** [comment]
Hi, sorry for the late reply.   
While running quantization with `inc_bench`, the `diagnosis` option will be default set as `true`. 
![image](https://user-images.githubusercontent.com/51692656/209632253-045f6867-43d6-409a-b61c-e25fc89f2f03.png) 
So the tool will do diagnosis after tuning, it's going to dump a lot of information of data distribution which is quite memory consuming.    
During our debugging on PC, it usually failed after dump 1/3 node info of ssd resnet50, we think it's due to out of memory. 
![image](https://user-images.githubusercontent.com/51692656/209632714-833929f0-66a9-486e-b9d4-f09c8ab90292.png)   
  
**Solutions:** 
1. If you want to use `inc_bench`, please use a server with large memory.    
And we will also try to optimize this large data handling issue. Or may be give an option to close the `diagnosis` function. 
2. If you would like to run examples with [cmd](https://github.com/intel/neural-compressor/tree/master/examples/onnxrt/image_recognition/resnet50/quantization/ptq#quantization), it will work. Because you can customized the yaml, you can run the example without `diagnosis` function.

**Comment by R4ZZ3** [comment]
Thanks @chensuyue for your continued efforts on this.
I will try this again once I have time.
