### ISSUE TITLE
 sequence length is longer than the specified maximum sequence length for this model (2842 > 2048). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by jinz2014** [intel/neural-compressor#1521]
Hi

The command produces the error shown below.  Thanks for your suggestion.
```  
python run_clm_no_trainer.py
    --model EleutherAI/gpt-j-6B \
    --dataset NeelNanda/pile-10k \
    --seed 0 \
    --quantize \
    --approach weight_only \
    --woq_algo GPTQ \
    --woq_bits 4 \
    --woq_scheme asym \
    --woq_group_size 128 \
    --gptq_pad_max_length 2048 \
    --gptq_use_max_length \
    --gptq_debug 
```
sequence length is longer than the specified maximum sequence length for this model (2842 > 2048). Running this sequence through the model will result in indexing errors

**Comment by yiliu30** [comment]
Hi @jinz2014 , as we have enabled this example on both the [2.x APIs](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm) and [3.x APIs](https://github.com/intel/neural-compressor/tree/master/examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm), could you please provide the folder path of the example so that we can replicate the issue?

**Comment by yiliu30** [comment]
Thanks for providing the details, it seems to be a warning rather than an error.
Our implementation will double-check the input length and select partial input if it exceeds `model_max_length`.
If you are interested in the details, please refer to the code. https://github.com/intel/neural-compressor/blob/4239d3675fe833aa4d145ffb49dd938bdc4c8726/neural_compressor/adaptor/torch_utils/gptq.py#L341-L349

**Comment by yiliu30** [comment]
Hi @jinz2014,  since we haven't received a response for an extended period. we'll assume the issue has been resolved. Feel free to reopen it if needed. Thank you
