### ISSUE TITLE
RTN sym behavior is not aligned

### ISSUE THREAD

**Issue by wenhuach21** [intel/neural-compressor#1695]
There are different sym implementations,  one is gptq/autoround way, the other is awq/our-rtn way.

**Comment by xin3he** [comment]
@wenhuach21, Do you mean the problem of RTN/AWQ using zp=0 and GPTQ/AutoRound using zp=8?
Currently, INC provides two output formats for the WOQ model, one is to export the huggingface-popular format, and the other is the fake quantized format.
Since the output format is consistent between algorithms, the internal implementation becomes irrelevant. So we don't have a plan to align their behavior, I will close this issue. 
You can reopen it if you have further concerns.
