### ISSUE TITLE
shape is not match when prune head

### ISSUE THREAD

**Issue by jinggaizi** [intel/neural-compressor#525]
when i run gradient_sensitivity example in branch old_api_examples , "RuntimeError: shape '[32, 44, 8, 64]' is invalid for input of size 1081344" when runing at "x = x.view(*new_x_shape)". The bert-base-uncased has 12 heads and prune config is 8, however It doesn't seem to work

**Comment by chensuyue** [comment]
@YIYANGCAI please check this issue.

**Comment by YIYANGCAI** [comment]
Thanks for the issue! Actually this is because when original heads are removed, the MHA's inner attributes referred to attention heads have not been aligned with pruned QKV weights (for example, when bert-base's attention heads are 12, when pruned some heads with original codes, this value linked with MHA's attribute variable is still 12, thus when reshape it will raise errors)

We have currently enable more powerful head pruning feature in #632 , which helps you to remove head automatically. Plus, we enable FFN channel pruning which can gain noticeable acceleration. These features will be merged to INC-v2.2 soon.
