### ISSUE TITLE
PTQ calibration with a dataset & QAT Support for Stable diffusion Models

### ISSUE THREAD

**Issue by Sravanth-k27** [intel/neural-compressor#925]
Dear Author , I have seen the quantization code for SD Models and I have noticed that Calibration is being done on a single image and the UNET model is being calibrated on every timestep output .  Good results will be expected if calibration is done on a dataset instead of a single image & Also QAT support for Stable diffusion models will be beneficial.
Hoping to hear some good news from you

**Comment by PenghuiCheng** [comment]
For QAT， please refer https://github.com/intel/neural-compressor/blob/master/examples/pytorch/diffusion_model/diffusers/textual_inversion/distillation_for_quantization/README.md
 For PTQ calibration, you can rewrite calibration_func in https://github.com/intel/neural-compressor/blob/85931587d6fb9fd10d16e5c750dc5fdc519bda73/examples/pytorch/nlp/huggingface_models/text-to-image/quantization/run_diffusion.py#L253C17-L253C33, and use your data instead of args.calib_text.
